---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10
    driver:
      network:
        - ["private_network", {ip: "10.10.10.2"}]

suites:
  - name: default
    run_list:
      - recipe[serf::default]
    attributes:
      serf:
        agent:
          node_name: server1
          interface: eth1
